name: Go

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true
      - run: go test -race ./...
      - run: go vet ./...
      - name: Test Gin example
        working-directory: examples/gin
        run: go test ./...
